<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="34190" started-at="2019-11-05T08:55:30Z" finished-at="2019-11-05T08:56:04Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="34190" started-at="2019-11-05T08:55:30Z" finished-at="2019-11-05T08:56:04Z">
      <class name="com.training.sanity.tests.UniformadminloginUNF_048">
        <test-method status="PASS" signature="setUpBeforeClass()[pri:0, instance:com.training.sanity.tests.UniformadminloginUNF_048@724af044]" name="setUpBeforeClass" is-config="true" duration-ms="17" started-at="2019-11-05T14:25:30Z" finished-at="2019-11-05T14:25:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpBeforeClass -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.training.sanity.tests.UniformadminloginUNF_048@724af044]" name="setUp" is-config="true" duration-ms="10948" started-at="2019-11-05T14:25:30Z" finished-at="2019-11-05T14:25:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="Adminlogin1()[pri:0, instance:com.training.sanity.tests.UniformadminloginUNF_048@724af044]" name="Adminlogin1" duration-ms="23183" started-at="2019-11-05T14:25:41Z" finished-at="2019-11-05T14:26:04Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Success: You have modified products!
ﾃ余 but found [You have modified products! ﾃ余]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Success: You have modified products!
ﾃ余 but found [You have modified products! ﾃ余
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.training.pom.ProductsPOM.successmsg(ProductsPOM.java:136)
	at com.training.sanity.tests.UniformadminloginUNF_048.Adminlogin1(UniformadminloginUNF_048.java:102)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Adminlogin1 -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:com.training.sanity.tests.UniformadminloginUNF_048@724af044]" name="afterClass" is-config="true" duration-ms="8" started-at="2019-11-05T14:26:04Z" finished-at="2019-11-05T14:26:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.training.sanity.tests.UniformadminloginUNF_048@724af044]" name="afterMethod" is-config="true" duration-ms="0" started-at="2019-11-05T14:26:04Z" finished-at="2019-11-05T14:26:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- com.training.sanity.tests.UniformadminloginUNF_048 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
